/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zzl_mysecondproject_MainActivity */

#ifndef _Included_com_example_zzl_mysecondproject_MainActivity
#define _Included_com_example_zzl_mysecondproject_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zzl_mysecondproject_MainActivity
 * Method:    getStringFromZZl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zzl_mysecondproject_MainActivity_getStringFromZZl
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zzl_mysecondproject_MainActivity
 * Method:    getStringFromYing
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zzl_mysecondproject_MainActivity_getStringFromYing
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
